version: "3.9"

services:
  backend:
    build: ./backend
    container_name: devsphere_backend
    env_file: ./backend/.env
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - devsphere-net

  frontend:
    build: ./frontend
    container_name: devsphere_frontend
    restart: unless-stopped
    networks:
      - devsphere-net
    # NO PORTS HERE!

  nginx:
    build: ./nginx
    container_name: devsphere_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - devsphere-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
    
    entrypoint: "/bin/sh"

volumes:
  certbot-etc:

networks:
  devsphere-net:
    driver: bridge





# version: "3.9"

# services:
#   backend:
#     build: ./backend
#     container_name: devsphere_backend
#     restart: unless-stopped
#     env_file: ./backend/.env
#     ports:
#       - "4000:4000"
#     networks:
#       - devsphere-net

#   frontend:
#     build: ./frontend
#     container_name: devsphere_frontend
#     restart: unless-stopped
#     ports:
#       - "3000:80"    # Frontend accessible at http://SERVER_IP:3000
#     networks:
#       - devsphere-net
#     depends_on:
#       - backend

# networks:
#   devsphere-net:
#     driver: bridge




